const swaggerAutogen = require('swagger-autogen')({ openapi: '3.0.0' });

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/feriadosRoutes']

const doc = {
    info: {
        version: "1.0.0",
        title: "API de feriados",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8000",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "feriados",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
    },
    definitions: {
        feriados: {
            codigo_ibge: "1100072",
            data: '2025-01-01'
        },

    }
}

swaggerAutogen(outputFile, endpointsFiles, doc)